application:
  name: user-application
  project: microservices-example
  private-port: 8080
  public-port: 80

routers:
  - name: main-router
    routes:
      - application-name: user-application
        paths:
          - \/users\/.*
          - \/users
          - .*
