application:
  name: group-application
  project: microservices-example
  private-port: 8080
  public-port: 80

routers:
  - name: main-router
    routes:
      - application-name: group-application
        paths:
          - \/users\/.*\/groups\/.*
          - \/users\/.*\/groups
